spring.application.name=MyProject

spring.profiles.include=secret

kakao.redirect = http://localhost:8080/auth/login/kakao

# \uB370\uC774\uD130\uBCA0\uC774\uC2A4 \uC5F0\uACB0 \uC815\uBCF4
spring.datasource.url=jdbc:mysql://localhost:3306/kakaodb
spring.datasource.username=root
spring.datasource.password=@k33243364k@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA \uC124\uC815 (JPA \uC0AC\uC6A9 \uC2DC)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true